### ISSUE TITLE
Feature Request to have entry in mm.json for ip address to listen on (defaults to 127.0.0.1)

### ISSUE THREAD

**Issue by tinsami1** [MoneroOcean/meta-miner#2]
Claymore XMR miner throttles down its hashrate when pool address is 127.0.0.1.

While I could manually edit mm.js to change the ip address, it would mean that any update will overwrite this change.  So an entry in mm.json would be a better place to manage this.

**Comment by MoneroOcean** [comment]
Interesting. Will add this feature.

**Comment by MoneroOcean** [comment]
Fixed in v0.7. Please check if it helps.

**Comment by tinsami1** [comment]
Tested.  It works.  Claymore is not complaining anymore about local pool/proxy.  Closing ticket.
