### ISSUE TITLE
Miner socket error invalid algorithm: cuckaroo29s

### ISSUE THREAD

**Issue by hotheadhacker** [MoneroOcean/meta-miner#34]
unable to create mm.json after this error

```shell
mm.exe -p=gulf.moneroocean.stream:11024 --ethash="%GMINER% --algo ethash --proto stratum" --kawpow="%GMINER% --algo kawpow" --c29s="%GMINER% --algo cuckaroo29s" --c29b="%GMINER% --algo cuckaroo29b" --autolykos2="C:\Users\User\Desktop\gpu-miner-moneroocean/t-rex.exe -a autolykos2 -o stratum+tcp://localhost:3333 -u MY_WALLET -p gpu_miner"
```

**Comment by Spudz76** [comment]
They removed everything c29 family in 2.59 so you have to use maximum [2.58](https://github.com/develsoftware/GMinerRelease/releases/tag/2.58)

You might run into issues with there being no donation endpoint for the algo though (as happened to c29v which only worked for a week or two after it was cut out) and when it can't donate it exits constantly.  The c29v fix it to just use the MoneroVMiner instead.  Probably similar with this, find another c29s (Swap) miner app and use it instead.  And c29b (Bittube) was also chopped.
